---
- name: Install packages for BeeGFS client
  package:
    name:
    - elfutils-libelf-devel
    - beegfs-client
    - beegfs-helperd
    - beegfs-utils
    state: "present"
  become: true
  notify: Restart BeeGFS client service

- name: Store variable in updatable var
  set_fact:
    client: "{{ client_item }}"

- name: Set default client port
  set_fact:
    client: "{{ client | combine({'port_tcp': '8003'}) }}"
  when: client.port is not defined

- name: Set default client config path
  set_fact:
    client: "{{ client | combine({'config_path': '/etc/beegfs/beegfs-client-' + (client.mgmtd_host) + '.' + (client.mgmtd_port_tcp | string) + '.conf'}) }}"
  when: client.config_path is not defined

- name: Define client kernel build for IB
  lineinfile:
    path: "/etc/beegfs/beegfs-client-autobuild.conf"
    regexp: "^buildArgs="
    line: "{{ item.line }}"
  when: item.condition
  become: true
  with_items:
    - { line: "buildArgs=-j8 OFED_INCLUDE_PATH={{ beegfs_client_ofed_include_path }}", condition: "{{ beegfs_client_ofed_include_path }}" }
    - { line: "buildArgs=-j8", condition: "{{ not beegfs_client_ofed_include_path }}" }
  notify: Restart BeeGFS client service

- name: Ensure kernel development headers are present
  package:
    name: "{{ beegfs_distro_vars[ansible_os_family]['kernel_dev_pkg'] }}"
    state: present
  become: true
  notify: Restart BeeGFS client service

- name: Ensure gcc is installed
  package:
    name: "gcc"
    state: present
  become: true
  notify: Restart BeeGFS client service

- name: Ensure the BeeGFS mount point exists
  file:
    mode: 0755
    path: "{{ client.path }}"
    state: directory
  become: true
  notify: Restart BeeGFS client service

- name: Copy over beegfs-mounts config file
  template:
    src: beegfs-mounts.conf.j2
    dest: /etc/beegfs/beegfs-mounts.conf
    mode: 0644
  become: true
  notify: Restart BeeGFS client service

- name: Configure BeeGFS client
  template:
    mode: 0644
    src: beegfs-client.conf.j2
    dest: "{{ client.config_path }}"
  become: true
  notify: Restart BeeGFS client service

- name: Copy beegfs-client.service.d/ to /etc/systemd/system/
  copy:
    src: beegfs-client.service.d/
    dest: /etc/systemd/system/beegfs-client.service.d/
  notify: Restart BeeGFS client service
  become: true

- name: Rebuild the BeeGFS client kernel module
  command: /etc/init.d/beegfs-client rebuild
  args:
    creates: "{{ beegfs_kernel_module }}"
  become: true
  notify: Restart BeeGFS client service
